In [1]:
import numpy as np

A = np.array([[1, 5, 7, 8, 6.1, 9], [10, 4, 6, 9, 2, 12]])
print('The array A is:')
print(A)

print('A\'s dimension: ', A.ndim)
print('A\'s size: ', A.size)

A = A.astype(np.int32, copy=False)
print('\nChange the type of the array A from \'float\' to \'integer32\'')
print(A)

A[0, 4:6] = [11, 16]
A[1, 2:4] = [8, 10]
print('\nModify through index')
print(A)

print('\nAll the elements that are divisible by 3')
print(A[A % 3 == 0])

B = np.random.rand(5, 5)
print('\nGenerate a 5*5 matrix randomly')
print(B)
Bmax = np.max(B)
Bmin = np.min(B)
C = (B - Bmin) / (Bmax - Bmin)
print('Normalize it')
print(C)

d = np.random.rand(12)
d.sort()
d = d[1: -1]
print('\nA vector from 0 to 1 (not including 0 and 1) of size 10')
print(d)

The array A is:
[[ 1.   5.   7.   8.   6.1  9. ]
 [10.   4.   6.   9.   2.  12. ]]
A's dimension:  2
A's size:  12

Change the type of the array A from 'float' to 'integer32'
[[ 1  5  7  8  6  9]
 [10  4  6  9  2 12]]

Modify through index
[[ 1  5  7  8 11 16]
 [10  4  8 10  2 12]]

All the elements that are divisible by 3
[12]

Generate a 5*5 matrix randomly
[[0.97249726 0.21968643 0.04080138 0.91352687 0.1080323 ]
 [0.82140653 0.43636783 0.45582199 0.47291526 0.46540963]
 [0.89954933 0.54833539 0.4950661  0.13831361 0.71584153]
 [0.42007941 0.97608085 0.22069387 0.50449949 0.77407228]
 [0.93408953 0.13426142 0.38600472 0.28807887 0.09401165]]
Normalize it
[[0.99616842 0.19126374 0.         0.93311734 0.07188324]
 [0.83462235 0.42293931 0.44373967 0.46201578 0.45399077]
 [0.91817256 0.54265493 0.48569944 0.10425999 0.72175235]
 [0.40552374 1.         0.19234089 0.49578562 0.78401261]
 [0.95510291 0.0999274  0.36909111 0.26438888 0.05689237]]

A vector from 0 to 1 (not including 0 and 

In [2]:
import pandas as pd

s1 = pd.Series([18.5, 20, 24, 18, 15, 14, 16], index = ['周一', '周二', '周三', '周四', '周五', '周六', '周日'])
print('Create a Series')
print(s1)

print('\nTemperature from Tue to Thu')
print(s1[1: 4])

print('\nTemperature greater than 18 ℃')
print(s1[s1 > 18])

df_list = [('cat', 2.5, 1, 'yes'),
           ('cat', 3.0, 3, 'yes'),
           ('snake', 0.5, 2, 'no'),
           ('dog', np.nan, 3, 'yes'),
           ('god', 5.0, 2, 'no'),
           ('cat', 2.0, 3, 'no'),
           ('snake', 4.5, 1, 'no'),
           ('cat', np.nan, 1, 'yes'),
           ('dog', 7.0, 2, 'no'),
           ('dog', 3.0, 1, 'no')]
df_column = ['animal', 'age', 'visits', 'priority']
df_index = list(chr(i) for i in range(97,107))     # Use ASCII code to traverse a to j
df = pd.DataFrame(df_list, columns = df_column, index = df_index)
print('\nCreate a DataFrame')
print(df)

print('\nFetch the \'animal\' and \'age\' columns')
print(df[['animal','age']])

print('\nFetch the \'animal\' and \'age\' columns with index of rows[3, 4, 8]')
print(df.loc[df.index[[3,4,8]],['animal','age']])

print('\nFetch the row with missing \'age\' value')
print(df[df['age'].isnull()])

print('\nThe sum of data in \'visits\' column')
print(df['visits'].sum())

print('\nThe number of each animal')
print(df.value_counts('animal'))

Create a Series
周一    18.5
周二    20.0
周三    24.0
周四    18.0
周五    15.0
周六    14.0
周日    16.0
dtype: float64

Temperature from Tue to Thu
周二    20.0
周三    24.0
周四    18.0
dtype: float64

Temperature greater than 18 ℃
周一    18.5
周二    20.0
周三    24.0
dtype: float64

Create a DataFrame
  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    god  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

Fetch the 'animal' and 'age' columns
  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    god  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

Fetch the 'animal' and 'age' columns with index of rows[3, 4, 8]
  animal  age
d    dog  NaN
e    god  5.0
i    dog  7.0

Fetch the row with missing 'age' value
  animal  age  visits